fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, stop: true }
    view:
        view_response_listener: true
        formats:
            json: true
            xml: false
            html: false
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': 409
